###
GET http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug


###
POST  http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug

{
    "name" :"test room 6",
    "price" : 10007,
    "desc" : "sdffaaf",
    "roomNumbers" : 1044
}

###
GET http://localhost:5000/api/rooms/674495f27d7debe418e9f67f


###
PUT http://localhost:5000/api/rooms/674495f27d7debe418e9f67f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug


{
    "name" : "UpdatedName",
    "price": 10000
}

###
DELETE http://localhost:5000/api/rooms/674495f27d7debe418e9f67f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug
###
GET http://localhost:5000/api/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug


###
GET http://localhost:5000/api/bookings/675db7652bb2c783d2ab05ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug


###
POST  http://localhost:5000/api/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug


{
    "roomId" : "672afa655a4d81c9ae373269",
    "name" : "Sundaravel",
    "email" : "sundarvel.kasi@gmail.com",
    "checkInDate" : "2024-11-11",
    "checkOutDate": "2024-11-12"
}


###
PUT http://localhost:5000/api/bookings/675e9b697f2ea14000d352c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug


{
    "name" : "updatedname",
    "email": "updated@gmail.com"
}

###
DELETE http://localhost:5000/api/bookings/6750157f2afdd994d9934649
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug

###
GET http://localhost:5000/api/users 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug


###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "sundaravel",
    "email": "sundarvel7203@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email" : "sundarvel7203@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMDk1NTc2Mn0.NXLN-yo8O0Ta7OJ6kn595ZESv_3OBVftleVyTeho9Ug

###
GET http://localhost:5000/api/users/logout

#RAZOR PAYMENT

### 
POST  http://localhost:5000/api/payment/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmIzNGVlOGI1M2I1YWZhNDM1ZTczZCIsImlhdCI6MTczMjA4Mzk5N30.GLwdTohZ9WklpVMHNIK361scwdGgAHfYsCDFEcUGaPM

{
    "amount" : 10000
    
}
